nelmio_api_doc:
    documentation:
        info:
            title: BileMo.com
            description: Find the right phone, cause your company worth it !
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
